//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMARTSOLVEModels
    {
        public System.DateTime RPT_DATE { get; set; }
        public string EMP_NO { get; set; }
        public int METRIC_ID { get; set; }
        public string VALUE { get; set; }
        public int Company_ID { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
    }
}
